# Generated by Django 4.1.1 on 2022-09-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LounaAdmin", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Article",
        ),
    ]
