# Generated by Django 4.1.1 on 2022-10-20 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LounaAdmin", "0009_alter_categorynode_articles_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InactiveNewsTellers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("after_time", models.TimeField(verbose_name="Переодичность рассылки")),
                ("text", models.CharField(max_length=500, verbose_name="Текст")),
            ],
            options={
                "verbose_name": 'Рассылки "спящему" клиенту',
                "verbose_name_plural": 'Рассылки "спящим" клиентам',
            },
        ),
        migrations.CreateModel(
            name="KeywordArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ключевое слово статьи",
                "verbose_name_plural": "Ключевое слово статьи",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SUCCSESSFUL_PAYMENT", "SUCCSESSFUL_PAYMENT"),
                            ("UNSUCCESSFUL_PAYMENT", "UNSUCCESSFUL_PAYMENT"),
                        ],
                        max_length=500,
                    ),
                ),
                ("text", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Уведомление об оплате",
                "verbose_name_plural": "Уведомления об оплате",
            },
        ),
        migrations.CreateModel(
            name="NoviceNewsTellers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("after_time", models.TimeField(verbose_name="Переодичность рассылки")),
                ("text", models.CharField(max_length=500, verbose_name="Текст")),
            ],
            options={
                "verbose_name": "Рассылка новичку",
                "verbose_name_plural": "Рассылку новичку",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID на сайте"
                    ),
                ),
                (
                    "chat_id",
                    models.IntegerField(blank=True, null=True, verbose_name="Чат ID"),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("ZERO", "Нет аккаунта на сайте"),
                            ("FIRST", "Не оформил триал"),
                            ("SECOND", "Триал оформлен"),
                            ("THIRD", "Оформил (продлил?) подписку"),
                            ("FOURTH", "Карта удалена сразу"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="Статус подписки",
                    ),
                ),
                (
                    "subscription_end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата окончания подписки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "Статья", "verbose_name_plural": "Статьи"},
        ),
        migrations.AlterModelOptions(
            name="categorynode",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.RemoveField(
            model_name="categorynode",
            name="children",
        ),
        migrations.AddField(
            model_name="categorynode",
            name="final",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="article",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name="categorynode",
            name="articles",
        ),
        migrations.AlterField(
            model_name="categorynode",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_rel",
                to="LounaAdmin.categorynode",
            ),
        ),
        migrations.AlterField(
            model_name="categorynode",
            name="valid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="keywords",
            name="text",
            field=models.CharField(max_length=64, verbose_name="Ключевое слово"),
        ),
        migrations.DeleteModel(
            name="Keyword_Article",
        ),
        migrations.AddField(
            model_name="keywordarticle",
            name="article_id",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="LounaAdmin.article",
                verbose_name="ID Статьи",
            ),
        ),
        migrations.AddField(
            model_name="keywordarticle",
            name="keywords_id",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="LounaAdmin.keywords",
                verbose_name="ID Ключевого слова",
            ),
        ),
        migrations.AddField(
            model_name="categorynode",
            name="articles",
            field=models.ManyToManyField(
                blank=True, related_name="art", to="LounaAdmin.article"
            ),
        ),
    ]
