# Generated by Django 4.1.1 on 2022-10-25 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LounaAdmin", "0010_inactivenewstellers_keywordarticle_notification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="registration_date",
            field=models.DateField(
                default=datetime.datetime(2022, 10, 25, 23, 11, 53, 78998),
                verbose_name="Дата регистрации",
            ),
        ),
    ]
