# Generated by Django 4.1.1 on 2022-10-25 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LounaAdmin", "0011_user_registration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="inactivenewstellers",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Загловок"
            ),
        ),
        migrations.AddField(
            model_name="novicenewstellers",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Загловок"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_date",
            field=models.DateField(
                default=datetime.datetime(2022, 10, 25, 23, 32, 37, 448934),
                verbose_name="Дата регистрации",
            ),
        ),
    ]
