# Generated by Django 4.1.1 on 2022-10-26 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "LounaAdmin",
            "0012_inactivenewstellers_title_novicenewstellers_title_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="inactivenewstellers",
            name="after_time",
            field=models.IntegerField(verbose_name="Переодичность рассылки"),
        ),
        migrations.AlterField(
            model_name="novicenewstellers",
            name="after_time",
            field=models.IntegerField(verbose_name="Переодичность рассылки"),
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_date",
            field=models.DateField(
                default=datetime.datetime(2022, 10, 26, 1, 7, 47, 347255),
                verbose_name="Дата регистрации",
            ),
        ),
    ]
